#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Mar  1 09:59:39 2018

@author: msubbiah
"""

import panda as pd
dat = pd.read_csv('data/folder/gapminder_gdp_europe.csv', index_col = 'country')

